# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redmine_prefix_issue_with_author}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Davis"]
  s.date = %q{2010-02-16}
  s.description = %q{Simple Redmine plugin that will convert an issue named like 'This is a bug' into 'Author Name - This is a bug'}
  s.email = %q{edavis@littlestreamsoftware.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "COPYRIGHT.txt",
     "CREDITS.txt",
     "GPL.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "config/locales/en.yml",
     "init.rb",
     "lang/en.yml",
     "lib/prefix_issue_with_author/patches/issue_patch.rb",
     "rails/init.rb",
     "test/test_helper.rb",
     "test/unit/lib/prefix_issue_with_author/patches/issue_patch_test.rb",
     "test/unit/sanity_test.rb"
  ]
  s.homepage = %q{https://projects.littlestreamsoftware.com/projects/redmine-misc}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{TODO}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Redmine plugin that will prefix the Issue subject with the author's name.}
  s.test_files = [
    "test/test_helper.rb",
     "test/unit/lib/prefix_issue_with_author/patches/issue_patch_test.rb",
     "test/unit/sanity_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

